### ISSUE TITLE
iAd.framework and AdSupport.framework 

### ISSUE THREAD

**Issue by jzeferino** [BranchMetrics/xamarin-branch-deep-linking-attribution#105]
Is iAd.framework and AdSupport.framework included in the Xamarin.iOS Binding?

**Comment by antonargunov** [comment]
@jzeferino yes, they included

**Comment by jzeferino** [comment]
To make use of the `BranchIOS.DelayInitToCheckForSearchAds();` the frameworks mentioned above need to be included, but I don't need the using `iAd` and `AdSupport` to make that call.

**Comment by antonargunov** [comment]
@jzeferino sorry for delay,
you need to add iAd, after adding you will have "search_ad_encoded".

Look please:
https://www.dropbox.com/s/o0jv3um2ac84vfi/Screenshot%202019-07-04%2010.35.36png?dl=0

**Comment by jzeferino** [comment]
Not sure if I understood this. 

I'm calling `BranchIOS.DelayInitToCheckForSearchAds();` but I didn't need the `using iAd;`. 

If I used that using this is what I get:

![Screenshot 2019-08-08 at 11 18 57](https://user-images.githubusercontent.com/10722952/62695549-7773f380-b9ce-11e9-8aef-70e4547f2c33.png)

**Comment by antonargunov** [comment]
compiler is too smart, it ignores libraries which program doesn't use, add for example:
iAd.ADBannerView aDBannerView = new ADBannerView();

**Comment by csalmi-branch** [comment]
@jzeferino does adding a line forcing it to use the iAD library help fix your issue?

**Comment by jzeferino** [comment]
I think my question was misinterpreted. 
I will rephrase:

To call `BranchIOS.DelayInitToCheckForSearchAds();`  the docs say that we require the frameworks (iAd.framework and AdSupport.framework) need to be included.

So if that binaries are packed with the library its cool to call `BranchIOS.DelayInitToCheckForSearchAds();`, correct?

**Comment by antonargunov** [comment]
Let me explain, method _BranchIOS.DelayInitToCheckForSearchAds()_  uses iAd library.
When we bind our native library, we don't add/pack any system libraries.
All system libraries already binded in Xamarin and is accessible from Xamarin by "using iAd;"

That means, you need to include iAd library in Xamarin else our method will work incorrectly.
But compiler is very smart and it does not add libraries which is not used. Compiler don't know about we use iAd in binded library. That is a reason why we need to add additional row with using any class/method from iAD library. It is just for compiler.

**Comment by jzeferino** [comment]
So bottom line is, if the developer needs to call `BranchIOS.DelayInitToCheckForSearchAds()` then it should add the line `using iAd;` no matter if compiler says it should be removed.

Agree?

**Comment by antonargunov** [comment]
```
using Foundation;
using UIKit;
using BranchXamarinSDK;
**using iAd;**
using BranchXamarinTestbed;

namespace BranchXamarinTestbed.iOS
{
	[Register ("AppDelegate")]
	public class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
	{
		public override bool FinishedLaunching (UIApplication application, NSDictionary launchOptions)
		{
			global::Xamarin.Forms.Forms.Init ();

                        **iAd.ADBannerView aDBannerView = new ADBannerView();**
                        BranchIOS.DelayInitToCheckForSearchAds();

			AppBUO appBUO = new AppBUO ();
                        BranchIOS.Init ("your_key", launchOptions, appBUO);

			LoadApplication (appBUO);

			return base.FinishedLaunching(application, launchOptions);
		}
	}
}
```
