### ISSUE TITLE
netstandard2.1

### ISSUE THREAD

**Issue by jzeferino** [BranchMetrics/xamarin-branch-deep-linking-attribution#109]
Any planx on updating the library to netstandard2.1?

If we add branch package into a netstandard project we get a warning like this:

>  Warning NU1701: Package 'Branch-Xamarin-Linking-SDK 5.0.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.1'. This package may not be fully compatible with your project.

**Comment by antonargunov** [comment]
Hello, I think we will update our SDK in this year.

**Comment by jzeferino** [comment]
let me know if I can help.

**Comment by thelist-eng** [comment]
@antonargunov any news on this?

**Comment by antonargunov** [comment]
@jzeferino use please last version of Xamarin SDK

**Comment by jzeferino** [comment]
I can confirm this is now update but I think you guys introduced a bug there, I will close this one and add a new issue for the bug. thank you
