### ISSUE TITLE
.NETStandard 2.0 Support

### ISSUE THREAD

**Issue by kunaldhande** [BranchMetrics/xamarin-branch-deep-linking-attribution#110]
I get this warning when trying to build an Xamarin Forms project with the latest Branch SDK.
I am using the latest version (4.3) of Xamarin Forms

warning NU1701: Package 'Branch-Xamarin-Linking-SDK 5.0.9' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by antonargunov** [comment]
this is a not error, this is a warning because our library is PCL library.
we are working under netstandard library right now.

**Comment by antonargunov** [comment]
@kunaldhande use please latest version of Xamarin SDK
