### ISSUE TITLE
Install receiver API deprecated by google

### ISSUE THREAD

**Issue by AntRemo** [BranchMetrics/xamarin-branch-deep-linking-attribution#114]
Creating this as a reminder to update the Xamarin package.

Google details:
https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html

Relates to:
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/778
https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/issues/171

Thanks 🙏

**Comment by antonargunov** [comment]
@AntRemo update please Xamarin SDK, we added support of "Play Install Referrer API" in latest version.
