### ISSUE TITLE
Version 7.0.0 introduced bug

### ISSUE THREAD

**Issue by jzeferino** [BranchMetrics/xamarin-branch-deep-linking-attribution#116]
When compiling with (Azure devops in this case):
iOS 13.2
mono 6.4.0.208 
and Xamarin iOS 13.4.0.2

got this error:

`2020-02-26T15:12:39.7176950Z MTOUCH : error MT2101: Can't resolve the reference 'ObjCRuntime.TrampolineBlockBase', referenced from the method 'IOSNativeBranch.BNCNetworkOperationProtocol IOSNativeBranch.IBNCNetworkServiceProtocol::NetworkOperationWithURLRequest(Foundation.NSMutableUrlRequest,System.Action1<IOSNativeBranch.BNCNetworkOperationProtocol>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. `

**Comment by antonargunov** [comment]
@jzeferino update please Xamarin SDK, we uploaded new version
