### ISSUE TITLE
InvalidCastException when adding custom data to branch event.

### ISSUE THREAD

**Issue by bdavidsonJbs** [BranchMetrics/xamarin-branch-deep-linking-attribution#122]
The following code will throw an InvalidCastException whenever the SendEvent method is called.

`       
 public void TrackEvent(string eventName, Dictionary<string, string> data)
{
            var branch = Branch.GetInstance();
            var branchEvent = new BranchEvent(eventName);

            if (data != null && data.Any())
            {
                foreach (var item in data)
                {
                    // Adding item to event.
                    branchEvent.AddCustomData(item.Key, item.Value);
                }
            }

            // This is where the crash occurs!!!!
            branch.SendEvent(branchEvent);
        }`

![image](https://user-images.githubusercontent.com/62718737/77683859-1140de80-6f67-11ea-98cd-930c9415bb4e.png)

**Comment by antonargunov** [comment]
@bdavidsonJbs update please Xamarin SDK to version 7.0.3
