### ISSUE TITLE
Revenue isn't getting tracked in Commerce events, but Tax is for Android devices.

### ISSUE THREAD

**Issue by ktakasug24** [BranchMetrics/xamarin-branch-deep-linking-attribution#128]
Running into a strange tracking issue: Revenue isn't getting tracked in Commerce events, but Tax is for Android devices.

Both Tax and Revenue are cast as float:
https://github.com/BranchMetrics/xamarin-branch-deep-linking-attribution/blob/4c7a99db1dd4f636017f871517943d3cdb311a84/Branch-Xamarin-SDK/Model/BranchEvent.cs#L54

Then getDouble():
https://github.com/BranchMetrics/xamarin-branch-deep-linking-attribution/blob/9c3bb24b35aaefb844ac51048c6cf1fbf2d81d27/Branch-Xamarin-SDK.Droid/BranchAndroidUtils.cs#L209

![GithubBranch](https://user-images.githubusercontent.com/68077023/87071850-b064ab80-c1cf-11ea-92b1-059ce647ddb5.jpg)

![GithubBranch2 ](https://user-images.githubusercontent.com/68077023/87071985-e4d86780-c1cf-11ea-9dbd-123973f4db14.png)

**Comment by BranchJShek** [comment]
typo commit merged
